### ISSUE TITLE
msg.image is not working, but msg.attachment does

### ISSUE THREAD

**Issue by ThinkPadNL** [RayPS/node-red-contrib-pushover#24]
Hi @RayPS ,

There seems to be a typo in the [documentation](https://flows.nodered.org/node/node-red-contrib-pushover).
On that page it is said to use `msg.image` to attach a picture to a message. However, when i specify that parameter (with a path of a local JPEG picture file that does exists), it is ignored and no image is being attached to the message. But when i provide the same path as `msg.attachment` to the Pushover node, it is working like it should.

I think the documentation should be adjusted accordingly.

**Comment by RayPS** [comment]
Hello, it seems like you are using the built-in [official pushover node](https://flows.nodered.org/node/node-red-node-pushover).
The document you were looking at is our `node-red-contrib-pushover` node.
We aim for provide a full feature support for Pushover, the API is incompatible from the official node.

**Comment by ThinkPadNL** [comment]
Ah i see now, small detail in the name indeed. I am not using yours but the other one.
So no mistake in the documentation, but mistake on my side for using the wrong reference page.

Thanks for your reply.
