### ISSUE TITLE
All key pairs named "My Pushover Keys"...

### ISSUE THREAD

**Issue by deggle** [RayPS/node-red-contrib-pushover#4]
...which makes is quite hard to tell which is which!

No box to give a pair a name, so they all get listed the same.

Hopefully a quick fix?

**Comment by RayPS** [comment]
Definitely a bug, this will be fixed soon.

**Comment by RayPS** [comment]
This issue is now fixed, i was forgot the `name` field. Sorry for that stupid mistake.
