### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by johntdyer** [RayPS/node-red-contrib-pushover#8]
So I am trying to get this working and I have put in my API key, a title, and under name I have put "msg.payload" but I always seem to get the following error. 

```log
"Pushover error: ["user identifier is not a valid user, group, or subscribed user key"]"
```

Any idea what I am doing wrong ?

**Comment by RayPS** [comment]
This error is a response from Pushover, make sure your keys are correct.

**Comment by johntdyer** [comment]
I’ve tried creating a device and using that key and using the primary api key for my account.  Neither seem to work...

**Comment by RayPS** [comment]
Can you test your key by using curl?
```bash
curl -X "POST" "https://api.pushover.net/1/messages.json" \
     -F "user=xxxxxxxxxxxxxxxxxxxxxxxx" \
     -F "token=xxxxxxxxxxxxxxxxxxxxxxxx" \
     -F "title=Test" \
     -F "message=Test"
```

**Comment by johntdyer** [comment]
Perhaps I am being dense but where does the user value come from ? I have tried the name of the device, my email, and just about everything else I could think of ....

**Comment by RayPS** [comment]
Both `user` and `token` keys is a 30 length string, you can found them in https://pushover.net
